// Mocks generated by Mockito 5.4.4 from annotations
// in gongbab/test/app/ui/phone_number_input/phone_number_input_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:connectivity_plus/connectivity_plus.dart' as _i12;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i13;
import 'package:gongbab/data/auth/auth_token_manager.dart' as _i14;
import 'package:gongbab/domain/entities/check_in/kiosk_check_in.dart' as _i11;
import 'package:gongbab/domain/entities/lookup/employee_lookup.dart' as _i9;
import 'package:gongbab/domain/entities/status/kiosk_status.dart' as _i6;
import 'package:gongbab/domain/repositories/kiosk_repository.dart' as _i2;
import 'package:gongbab/domain/usecases/get_employee_candidates_usecase.dart'
    as _i8;
import 'package:gongbab/domain/usecases/get_kiosk_status_usecase.dart' as _i3;
import 'package:gongbab/domain/usecases/kiosk_check_in_usecase.dart' as _i10;
import 'package:gongbab/domain/utils/result.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKioskRepository_0 extends _i1.SmartFake
    implements _i2.KioskRepository {
  _FakeKioskRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetKioskStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetKioskStatusUseCase extends _i1.Mock
    implements _i3.GetKioskStatusUseCase {
  MockGetKioskStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KioskRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeKioskRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.KioskRepository);

  @override
  _i4.Future<_i5.Result<_i6.KioskStatus>> execute({
    required int? restaurantId,
    required String? kioskCode,
    required String? clientTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #restaurantId: restaurantId,
            #kioskCode: kioskCode,
            #clientTime: clientTime,
          },
        ),
        returnValue: _i4.Future<_i5.Result<_i6.KioskStatus>>.value(
            _i7.dummyValue<_i5.Result<_i6.KioskStatus>>(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #restaurantId: restaurantId,
              #kioskCode: kioskCode,
              #clientTime: clientTime,
            },
          ),
        )),
      ) as _i4.Future<_i5.Result<_i6.KioskStatus>>);
}

/// A class which mocks [GetEmployeeCandidatesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetEmployeeCandidatesUseCase extends _i1.Mock
    implements _i8.GetEmployeeCandidatesUseCase {
  MockGetEmployeeCandidatesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KioskRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeKioskRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.KioskRepository);

  @override
  _i4.Future<_i5.Result<_i9.EmployeeLookup>> execute({
    required int? restaurantId,
    required String? phoneLastFour,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #restaurantId: restaurantId,
            #phoneLastFour: phoneLastFour,
          },
        ),
        returnValue: _i4.Future<_i5.Result<_i9.EmployeeLookup>>.value(
            _i7.dummyValue<_i5.Result<_i9.EmployeeLookup>>(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #restaurantId: restaurantId,
              #phoneLastFour: phoneLastFour,
            },
          ),
        )),
      ) as _i4.Future<_i5.Result<_i9.EmployeeLookup>>);
}

/// A class which mocks [KioskCheckInUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockKioskCheckInUseCase extends _i1.Mock
    implements _i10.KioskCheckInUseCase {
  MockKioskCheckInUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KioskRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeKioskRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.KioskRepository);

  @override
  _i4.Future<_i5.Result<_i11.KioskCheckIn>> execute({
    required int? restaurantId,
    required int? employeeId,
    required String? kioskCode,
    required String? clientTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #restaurantId: restaurantId,
            #employeeId: employeeId,
            #kioskCode: kioskCode,
            #clientTime: clientTime,
          },
        ),
        returnValue: _i4.Future<_i5.Result<_i11.KioskCheckIn>>.value(
            _i7.dummyValue<_i5.Result<_i11.KioskCheckIn>>(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #restaurantId: restaurantId,
              #employeeId: employeeId,
              #kioskCode: kioskCode,
              #clientTime: clientTime,
            },
          ),
        )),
      ) as _i4.Future<_i5.Result<_i11.KioskCheckIn>>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i12.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i13.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i4.Stream<List<_i13.ConnectivityResult>>.empty(),
      ) as _i4.Stream<List<_i13.ConnectivityResult>>);

  @override
  _i4.Future<List<_i13.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i4.Future<List<_i13.ConnectivityResult>>.value(
            <_i13.ConnectivityResult>[]),
      ) as _i4.Future<List<_i13.ConnectivityResult>>);
}

/// A class which mocks [AuthTokenManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthTokenManager extends _i1.Mock implements _i14.AuthTokenManager {
  MockAuthTokenManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveTokens(
    String? accessToken,
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [
            accessToken,
            refreshToken,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveRestaurantInfo(
    int? restaurantId,
    String? kioskCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRestaurantInfo,
          [
            restaurantId,
            kioskCode,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
